### ISSUE TITLE
API參數帶錯

### ISSUE THREAD

**Issue by XuPeiYao** [lightup-studio/AKI-ERP-Frontend#7]
分頁參數中的Offset應當為PageIndex x PageItemCount
即假設頁有10筆資料，第二頁的Offset則應為   (2-1)x10

**Comment by SHANG-TING** [comment]
https://github.com/lightup-studio/AKI-ERP-Frontend/pull/8/commits/f9a95e6998980cb5aafdc4bdb14f0ea3fc9b04af

**Comment by SHANG-TING** [comment]
This issue will be fixed in the next version 🙏
